; PHP — preset dev.
display_errors=1
display_startup_errors=1
error_reporting=E_ALL
log_errors=1
error_log=/dev/stderr

memory_limit=512M
max_execution_time=60
post_max_size=16M
upload_max_filesize=16M

date.timezone=Africa/Tunis

[opcache]
opcache.enable=1

[session]
session.gc_maxlifetime=86400
